spring.application.name=auth-service
server.port=8081


spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.profiles.include=local

jwt.secret=J1puBetMouDpy7#ToTBouMup159753456Mo)l(Ho11odyMatbOb3tomJLu3aCMeLLIaPuk1235569852525555jhg
jwt.refresh.expiration=3600000
jwt.access.expiration=604800000

logging.module=AUTH-SERVICE
logging.output=file
logging.filePath=logs/auth-service.log