spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=dilya2006
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.profiles.include=local

jwt.secret=J1puBetMouDpy7#ToTBouMup159753456Mo)l(Ho11odyMatbOb3tomJLu3aCMeLLIaPuk1235569852525555jhg
jwt.refresh.expiration=3600000
jwt.access.expiration=604800000