version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis_composed
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  minio:
    image: minio/minio
    container_name: minio_composed
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_composed
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:17-alpine
    container_name: postgres_composed
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sql:/docker-entrypoint-initdb.d/init-multiple-databases.sql

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway_composed
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - auth-service
      - booking-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service_composed
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - postgres

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking_service_composed
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - minio
      - rabbitmq

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics_service_composed
    depends_on:
      - rabbitmq
    env_file:
      - .env

  notification-service:
    build:
      context: ./notification-service
    container_name: notification_service_composed
    depends_on:
      - rabbitmq
    env_file:
      - .env

volumes:
  redis_data:
  minio_data:
  rabbitmq_data:
  postgres_data: