<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thanks for register</title>
</head>
<body>
<h1>Подтверждение почты:</h1>
<img src="//kpfu.ru//portal/docs/F_1313344075/02_logotip_3_stroki_cvetnoj.png"/>
<h2><a href="http://localhost:8080/confirm/${confirmCode}">Подтверждение почты</a> </h2>
</body>
</html>