server:
  port: 8080 # порт для гэйтвэй

jwt:
  secret: "J1puBetMouDpy7#ToTBouMup159753456Mo)l(Ho11odyMatbOb3tomJLu3aCMeLLIaPuk1235569852525555jhg"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**,/api/v1/auth/**

        - id: booking-service-public
          uri: http://localhost:8082
          predicates:
            - Path=/css/**,/image/**,/js/**

        - id: booking-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/booking-service/v3/api-docs,/booking-service/v3/api-docs/**
          filters:
            - RewritePath=/booking-service/(?<remaining>.*),/${remaining}

        - id: booking-service-protected
          uri: http://localhost:8082
          predicates:
            - Path=/**
          filters:
            - AuthenticationFilter #кастомный фильтр для проверки jwt
            - RewriteResponseHeader=Location, ^http://localhost:8082(.*), $1

springdoc:
  swagger-ui:
    urls:
      - name: Booking Service API
        url: /booking-service/v3/api-docs