server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**,/api/v1/auth/**,/sign-in,/sign-up

        - id: auth-service-docs
          uri: http://auth-service:8081
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - RewritePath=/auth-service/v3/api-docs, /v3/api-docs

        - id: booking-service-public
          uri: http://booking-service:8082
          predicates:
            - Path=/css/**,/image/**,/js/**

        - id: booking-service-docs
          uri: http://booking-service:8082
          predicates:
            - Path=/booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service/v3/api-docs, /v3/api-docs

        - id: booking-service-protected
          uri: http://booking-service:8082
          predicates:
            - Path=/**
          filters:
            - AuthenticationFilter
            - RewriteResponseHeader=Location, ^http://booking-service:8082(.*), $1

springdoc:
  swagger-ui:
    urls:
      - name: Booking Service
        url: /booking-service/v3/api-docs

      - name: Auth Service
        url: /auth-service/v3/api-docs