spring.application.name=booking_service
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=dilya2006
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
storage.path=C:\\files

spring.mail.username =ArtuANigmatullin@kpfu.ru
spring.mail.password = bvxrjoyaicdnkbxn
spring.mail.port = 465
spring.mail.host = smtp.yandex.ru

spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.allow8bittime = true
spring.mail.properties.mail.smtp.ssl.trust = smtp.yandex.ru
spring.mail.properties.mail.debug = true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


logging.module=BOOKING-SERVICE
logging.output=file
logging.filePath=logs/booking-service.log
