spring.application.name=booking_service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework.security=DEBUG
spring.profiles.include=local

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis


minio.url=http://localhost:9000
minio.access.key=minioadmin
minio.secret.key=minioadmin
minio.bucket.name=images

logging.module=BOOKING-SERVICE
logging.output=file
logging.filePath=logs/booking-service.log
