<#import "../layout.ftlh" as layout>
<@layout.mainLayout title="500 - Ошибка сервера">
    <div class="error-container">
        <h1 class="error-code">500</h1>
        <h2 class="error-title">Внутренняя ошибка сервера</h2>
        <p class="error-message">Мы уже получили уведомление и работаем над исправлением. Приносим свои извинения!</p>
        <a href="/home" class="error-btn">На главную</a>
    </div>
</@layout.mainLayout>