--
-- PostgreSQL database dump
--

\restrict jCcfe4BgF4dVLB7sjdyvX1tXuskDUL42LaPlD2CyIEnSBGyh6zY2bcryn22kNCm

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    exp_date timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_auth; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_auth (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_auth_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users_auth OWNER TO postgres;

--
-- Name: users_auth_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_auth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_auth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, exp_date, revoked, token, user_id) FROM stdin;
13	2026-05-26 10:26:54.932106+03	f	3775c203-716d-48c3-ac6f-a1caf1dd1ffa	6
23	2026-05-27 21:02:57.606746+03	f	8ed3078c-c1ed-4195-ab0c-63dc7a848e57	7
25	2026-05-28 14:58:25.030392+03	f	4ff32b24-9314-47ec-bf78-b17eaf9be421	2
26	2026-05-28 15:03:49.658915+03	f	dd1306ae-e78f-484a-8f13-6501df2f5d11	1
\.


--
-- Data for Name: users_auth; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_auth (id, email, name, password, role) FROM stdin;
1	ab@mail.ru	ртур	$2a$10$l5x0GwoMMl4kschhlylBZ.KZ0kv0qVKUJdUIrZapCeY0E8vGT8YOy	ROLE_USER
2	a@mail.ru	артууууур	$2a$10$u91sFN.2pe4Q6d63Vt7sN.FDthkktm.PFKWg3R47dpGX.clGmbiyW	ROLE_ADMIN
6	d@mail.ru	dilyara	$2a$10$ogDr41xn1K0..F75IIvp4ONhP1IaBkuGcIyO0dFjXdq9d5sRJoE7e	ROLE_USER
7	arturinrussia@gmail.com	антон	$2a$10$o15SjomagNKg/RyoQi8uiO4QkIeUdHuhbF41y5uKSAZdsyFSpad9u	ROLE_USER
\.


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 26, true);


--
-- Name: users_auth_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_auth_id_seq', 7, true);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: users_auth ukg4edwaes63j30uixka1j2fm9n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_auth
    ADD CONSTRAINT ukg4edwaes63j30uixka1j2fm9n UNIQUE (email);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: users_auth users_auth_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_auth
    ADD CONSTRAINT users_auth_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens fknsnd5bbh9y9kbkfkoevvhl02t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fknsnd5bbh9y9kbkfkoevvhl02t FOREIGN KEY (user_id) REFERENCES public.users_auth(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict jCcfe4BgF4dVLB7sjdyvX1tXuskDUL42LaPlD2CyIEnSBGyh6zY2bcryn22kNCm

